# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.1.0
_src_path: https://github.com/delorenj/CommonProject
project_description: 'Voice-driven mobile-first Zellij client '
project_name: Perth
